Dependencies update, typescript check tests, fix hoc inference (#1402)
* Fix TS4053 error with latest @types/react

Error:(45, 3) TS4053: Return type of public method from exported class has or is using name 'React.ReactElement' from external module "react-apollo/node_modules/@types/react/index" but cannot be named.

* typos

* Update all non-major versions

* move prettier to config file for external tool use, add tslint —fix to lint-fix script

* run lint-fix (prettier + tslint fix)

* fix cli deprecation for tslint

* fix lint error

* make sure sources are linted in the `test` script

* reuse tsconfig.json for type checking to avoid false positives

Change lib to 2017 fixes the AsyncIterable problem

* add changelog to satisfy danger before continuing

* babel-jest and ts-jest upgrade success

* redux-form and redux-loop upgraded

* lint-staged, danger updated

* cheerio updated

* babel-preset-react-native updated

* revert danger to 1.2.0 for the moment

* fix duplicate/conflicting export of getDataFromTree namespace

* broken - Symbol(id) is making it into props.data

* Remove unused enzyme-to-json

* revert tsconfig lib back to es2015 from es2017

* revert prettier config to default line length (not matching tslint’s 140 max)

* New jasmine custom matcher added - typescript still unhappy about it.

- Reorganized generic typings file into a folder with module per file layout
- Moved jest setup files under test/setup (with matcher)

* fix unnecessary redefinition of React.ComponentType as CompositeComponent

* Fix graphql decorator inference and tie together parameterized types (breaking change)

Fixes issue #755, Supercedes PR #1395 - and making progress towards valid typescript in the test directory #1404

* graphql inference looks to working (so far so good)

* Expose TChildProps on the outside, allow inference to determine props on the inside

* formating/lint-staged fighting?

* lint-fix

* once-over completed on api-test

* api.test is working/typechecking

* run prettier on all changes

* unify on one tsconfig and just cleanup after compile - reduces chances of differences in test type checking

* api.test back to type checking - seems like other triple slash directives interfered

* errors.test and queries.test work

* noUnusedParams cannot be used because the simplest react component is (props) => null

* checkpoint

* lifecycle.test type checked

* checkpoint test type checks - queries directory working

* test mutations type check

* test - client-option and fragments complete

* make purpose of file more clear

* consistent naming of TData instead of TResult which populates the DataValue

* disallow synthetic defaults to raise errors sooner

* TData and TGraphQLVariables naming consistency. Expose DataValue separately, Expose stronger typed ChildDataProps and ChildMutateProps

* type checked shared-operations

* add stateless function usage example

* wip statics

* fix prettier text jumping and specify the default width just for clarity

* fix shouldResubscribe props

* subscriptions test type checks

* mobx test works, but redux form tests were out of date. typescript updates applied but needs more work

* ApolloProvider.test type checks

* server/index.test type checks

* remove redux integration test

* remove more integration tests, server tests type check

* component.test type checks

* flow really out of date - some updates to remove redux but not perfect

* yarn type-check runs

* fix compile script

* tests are linted

* consolidate test-utils

* examples are not running in master by jest, but evidently the jest upgrade sees this config and needs more work or example module resolution

* update typescript usage

* yarn test passes

* change jest config to see if it impacts danger

* update changelog

* rename custom matcher to easier toEqualJson

* Updated danger

* try to appease timing on travis (test works locally)

* flaky async timing experiment on travis

* give additonal gap for pollingInterval to execute on travis (works locally)

* make sure some files don’t make it in the package

* cleanup publish steps (split for testing)

* split deploy for script testing

* as big of a gap as we can to allow travis to catch the last polling